import os
import json
import re
import logging
from google import genai

logger = logging.getLogger("redactpro.gemini")

def get_custom_rules_from_instructions(instructions: str) -> dict | None:
    """
    Use Gemini to parse instructions and output custom regex rules.
    If the instructions don't make sense or are empty, returns None.
    """
    if not instructions or not instructions.strip():
        return None
        
    api_key = os.environ.get("GEMINI_API_KEY")
    if not api_key:
        logger.warning("GEMINI_API_KEY not set. Falling back to default rules.")
        return None
        
    try:
        client = genai.Client(api_key=api_key)
        
        prompt = f"""
You are an AI assistant helping a redaction tool. The user has provided custom instructions on what to redact.
Instructions: "{instructions}"

If the instructions make sense for redacting text (e.g., "redact my email", "hide phone numbers", "redact John Doe"), you must output a JSON object where keys are descriptive categories and values are arrays of Python regular expression strings that would match the user's request. 

For example, if the user says "redact email addresses", output:
{{
  "custom_emails": ["[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\\\.[a-zA-Z]{{2,}}"]
}}

If the user asks to redact a specific name like "John", output:
{{
  "custom_name": ["(?i)\\\\bJohn\\\\b"]
}}

If the instructions do not make sense for redaction or are just gibberish, return an empty JSON object: {{}}.
Output ONLY valid JSON without markdown formatting or anything else.
"""
        response = client.models.generate_content(
            model='gemini-3.6-flash',
            contents=prompt,
        )
        
        text = response.text.strip()
        print("\n=== GEMINI API RAW OUTPUT ===")
        print(text)
        print("=============================\n")
        
        if text.startswith("```json"):
            text = text[7:]
        if text.endswith("```"):
            text = text[:-3]
            
        rules_dict = json.loads(text.strip())
        
        if not rules_dict:
            return None
            
        compiled_rules = {}
        for category, patterns in rules_dict.items():
            compiled_patterns = []
            for pattern in patterns:
                try:
                    compiled_patterns.append(re.compile(pattern))
                except re.error as e:
                    logger.error(f"Failed to compile regex generated by Gemini: {pattern} - {e}")
            if compiled_patterns:
                compiled_rules[category] = compiled_patterns
                
        return compiled_rules if compiled_rules else None
        
    except Exception as e:
        logger.error(f"Gemini API error: {e}")
        return None
